"""V10: proving the results page is what the generator writes, and nothing else."""

import pytest

import check_report


def test_a_hand_edited_page_is_caught(tmp_path, monkeypatch):
    page = tmp_path / "results.md"
    page.write_text("generated\n", encoding="utf-8")

    def fake_generate(out):
        out.write_text("generated\n", encoding="utf-8")
        return 0

    monkeypatch.setattr(check_report, "generate", fake_generate)
    assert check_report.differences(page) == []
    page.write_text("generated by hand\n", encoding="utf-8")
    assert check_report.differences(page) != []


def test_a_generator_that_refuses_is_reported(tmp_path, monkeypatch):
    page = tmp_path / "results.md"
    page.write_text("x", encoding="utf-8")
    monkeypatch.setattr(check_report, "generate", lambda out: 1)
    with pytest.raises(check_report.GeneratorRefused):
        check_report.differences(page)


def test_the_final_page_may_not_say_not_run(tmp_path):
    page = tmp_path / "results.md"
    page.write_text("## Agent\n\n⏳ not run\n", encoding="utf-8")
    assert check_report.unfinished(page) == ["⏳ not run"]
    page.write_text(
        "## Agent\n\n| L1 | 15 | 0.80 ± 0.02 | 3 not answered yet |\n", encoding="utf-8"
    )
    assert check_report.unfinished(page) == ["not answered yet"]
    page.write_text("## Agent\n\n| L1 | 15 | 0.80 ± 0.02 | |\n", encoding="utf-8")
    assert check_report.unfinished(page) == []


def test_the_final_gate_wants_every_answer_replayed():
    """A final page must read its retrieval ceiling from the replayed output for all of it."""
    covered, total = check_report.replay_gap()
    assert total > 0
    assert covered <= total
