"""Write docs/data_card.md from the generated data (spec §4.8).

Every number in the card is computed from data/raw/*.csv and the generator's intent file,
so the card cannot drift from the data. Re-run after any generator or vocabulary change.

Usage: python scripts/describe_data.py [--data data/] [--out docs/data_card.md]
"""

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
TABLES = [
    "employees",
    "reports",
    "tables",
    "report_table_edges",
    "table_table_edges",
    "metrics",
    "requests",
]
ABBREVIATION_TAGS = {"GM", "AOV", "NPS", "YoY", "MTD", "CSAT", "FTFR", "OTD", "DSO", "ROAS", "CPL"}
SAMPLE_COLUMNS = {
    "employees": ["employee_id", "full_name", "department", "title", "status", "manager_id", "successor_id", "start_date", "left_date"],
    "reports": ["report_id", "name", "department", "owner_id", "status", "refresh_status", "usage_30d", "tags", "description"],
    "tables": ["table_id", "name", "layer", "schema_name", "source_system", "owner_id", "row_count", "update_frequency", "description"],
    "report_table_edges": ["report_id", "table_id"],
    "table_table_edges": ["parent_table_id", "child_table_id", "transform_type"],
    "metrics": ["metric_id", "name", "aliases", "formula", "source_table_ids", "owner_id"],
    "requests": ["request_id", "title", "status", "department", "created_date", "closed_date", "resulting_report_id", "duplicate_of_request_id"],
}  # fmt: skip


def md_table(headers: list[str], rows: list[list[object]]) -> str:
    def cell(value: object) -> str:
        text = "" if value is None else str(value)
        return text.replace("|", "\\|").replace("\n", " ")

    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(cell(v) for v in row) + " |" for row in rows]
    return "\n".join(lines)


def shorten(text: str, limit: int = 70) -> str:
    return text if len(text) <= limit else text[: limit - 1] + "…"


def counts_table(series: pd.Series, label: str) -> str:
    counts = series.value_counts().sort_index()
    total = counts.sum()
    return md_table(
        [label, "rows", "share"], [[k, v, f"{v / total:.0%}"] for k, v in counts.items()]
    )


def ownership_walk(emp: pd.DataFrame, start: str, max_depth: int = 3) -> tuple[bool, int]:
    rows = emp.set_index("employee_id")
    current, hops = start, 0
    while rows.at[current, "status"] == "left":
        if hops == max_depth:
            return False, hops
        nxt = rows.at[current, "successor_id"] or rows.at[current, "manager_id"]
        current, hops = nxt, hops + 1
    return True, hops


def build_card(data_dir: Path) -> str:
    raw = {
        name: pd.read_csv(data_dir / "raw" / f"{name}.csv", dtype=str, keep_default_na=False)
        for name in TABLES
    }
    meta = json.loads((data_dir / "_meta.json").read_text(encoding="utf-8"))
    emp, rep, tab, req, met = (
        raw[k] for k in ["employees", "reports", "tables", "requests", "metrics"]
    )
    status_of = emp.set_index("employee_id")["status"]
    owner_status = rep["owner_id"].map(status_of)
    chains = meta["chains"]
    n_heads = len(chains["S1"]) + len(chains["S2"])
    n_heads += sum(len(chains[code]) for code in ("C2", "C3", "C4"))
    usage = rep["usage_30d"].astype(int)
    active = rep["status"] == "active"

    out: list[str] = []
    add = out.append
    add("# Data card: Northwind Motors synthetic BI metadata")
    add("")
    add(
        "> **All data here is synthetic.** It was generated from a fixed seed by "
        "`python -m metacompass.data.generate`, using hand-written vocabularies and templates. "
        "It contains no real company data, and Northwind Motors is a fictional company."
    )
    add("")
    add(
        f"Seed `{meta['seed']}` · generator `{meta['generator_version']}` · "
        f'reference date ("today") `{meta["reference_date"]}`. '
        "This card is generated by `scripts/describe_data.py`; do not edit it by hand."
    )
    add("")
    add("## Tables")
    add("")
    add(md_table(["table", "rows", "what one row is"], [
        ["employees", len(emp), "a person, current or former, with manager and successor links"],
        ["reports", len(rep), "a BI report with owner, status, refresh state and usage"],
        ["tables", len(tab), "a warehouse table in the staging, intermediate or mart layer"],
        ["report_table_edges", len(raw["report_table_edges"]), "a report reads a table"],
        ["table_table_edges", len(raw["table_table_edges"]), "data flows from a parent table into a child table"],
        ["metrics", len(met), "a business metric with aliases, definition, formula and source tables"],
        ["requests", len(req), "an analysis request to the data team"],
    ]))  # fmt: skip
    add("")
    add("## Distributions")
    add("")
    add("### Employees")
    add("")
    by_dept = emp.groupby(["department", "status"]).size().unstack(fill_value=0)
    add(
        md_table(
            ["department", "active", "left"],
            [[d, r["active"], r["left"]] for d, r in by_dept.iterrows()],
        )
    )
    add("")
    add("### Reports")
    add("")
    add(counts_table(rep["status"], "status"))
    add("")
    add(counts_table(rep["refresh_status"], "refresh_status"))
    add("")
    add(counts_table(rep["department"], "department"))
    add("")
    quantiles = usage.quantile([0.25, 0.5, 0.75, 0.9, 0.99]).round(0).astype(int)
    add(
        "`usage_30d` (views in the last 30 days) is long-tailed: "
        + ", ".join(f"p{int(q * 100)} = {v}" for q, v in quantiles.items())
        + f", max = {usage.max()}; {(usage[active] == 0).mean():.0%} of active reports had no views."
    )
    add("")
    departed_active = int((active & owner_status.eq("left")).sum())
    add(
        f"{departed_active} of {int(active.sum())} active reports "
        f"({departed_active / active.sum():.1%}) have an owner who has left the company. "
        f"That is the floor set by the {n_heads} succession-chain heads, who must own two active "
        "reports each; no other active report has a departed owner. For comparison, "
        f"{tab['owner_id'].map(status_of).eq('left').mean():.1%} of tables and "
        f"{met['owner_id'].map(status_of).eq('left').mean():.1%} of metrics have a departed owner."
    )
    add("")
    add("### Warehouse tables")
    add("")
    add(counts_table(tab["layer"], "layer"))
    add("")
    add(counts_table(tab["update_frequency"], "update_frequency"))
    add("")
    add("### Requests")
    add("")
    add(counts_table(req["status"], "status"))
    add("")
    add("## Ownership succession structures")
    add("")
    add(
        "Ownership of an asset is resolved by walking from the owner through `successor_id` "
        "(or `manager_id` when there is no successor) until an active employee is reached. "
        "Three hops still count as resolved; a fourth hop falls back to the department head."
    )
    add("")
    structure_rows = []
    descriptions = {
        "S1": "left → successor (active)",
        "S2": "left, no successor → manager (active)",
        "C2": "two leavers, then active successor or manager",
        "C3": "three leavers, then active successor",
        "C4": "four leavers; walk stops at the depth limit",
    }
    for code, text in descriptions.items():
        entries = meta["chains"][code]
        heads = entries if code in ("S1", "S2") else [chain[0] for chain in entries]
        leavers = len(entries) if code in ("S1", "S2") else sum(len(c) for c in entries)
        walks = {ownership_walk(emp, h) for h in heads}
        outcome = ", ".join(
            f"{'resolved' if ok else 'unresolved'} after {hops} hop(s)"
            for ok, hops in sorted(walks)
        )
        structure_rows.append([code, text, len(heads), leavers, outcome])
    add(
        md_table(
            ["code", "shape", "structures", "people who left", "walk from the first owner"],
            structure_rows,
        )
    )
    add("")
    add(f"Total employees who left: {int((emp['status'] == 'left').sum())}.")
    add("")
    add("## Deliberate noise")
    add("")
    tags = rep["tags"].str.split("|")
    noise_rows = [
        ["N1", "near-duplicate report names (e.g. *X* and *X – Detail*)", len(meta["near_duplicate_pairs"])],
        ["N2", "deprecated reports, each pointing to an active replacement", len(meta["deprecated_map"])],
        ["N3", "reports tagged with an abbreviation (GM, AOV, NPS, YoY, MTD, …)", int(tags.map(lambda t: bool(set(t) & ABBREVIATION_TAGS)).sum())],
        ["N4", "reports with a vague or stale description", len(meta["vague_description_reports"])],
        ["N5", "active reports whose last refresh failed", int((active & (rep["refresh_status"] == "failed")).sum())],
        ["N6", "analysis-request topic clusters with paraphrased titles", len(set(meta["request_topic_keys"].values()))],
        ["N7", "metrics without a documented formula", len(meta["null_formula_metrics"])],
    ]  # fmt: skip
    add(md_table(["code", "noise", "count"], noise_rows))
    add("")
    add(
        "N7 also covers `fct_budget_2026`, the only budget table, which holds the 2026 plan "
        "only, and a reserved pool of plausible report names and analysis topics that the "
        "generator never uses, for questions that look answerable but are not."
    )
    add("")
    add("### Near-duplicate and deprecated examples")
    add("")
    names = rep.set_index("report_id")["name"]
    examples = [[a, names[a], b, names[b]] for a, b in meta["near_duplicate_pairs"][:3]]
    examples += [[a, names[a], b, names[b]] for a, b in list(meta["deprecated_map"].items())[:3]]
    add(md_table(["report", "name", "paired with", "name"], examples))
    add("")
    add("## Sample records")
    add("")
    for name in TABLES:
        frame = raw[name]
        picks = sorted({0, len(frame) // 2, len(frame) - 1})
        columns = SAMPLE_COLUMNS[name]
        rows = [[shorten(str(frame.iloc[i][c])) for c in columns] for i in picks]
        add(f"### {name}")
        add("")
        add(md_table(columns, rows))
        add("")
    add("## Known limits")
    add("")
    for line in [
        "Text comes from templates and curated word lists, so wording repeats more than in a real catalog.",
        "Distributions are tidier than real life: exact status ratios, one owner per asset, no missing owners.",
        "Attrition is deliberately high (38 of 120 people left) so that every succession structure is present. "
        "Departed owners are kept to the minimum that structure forces (about a fifth of active reports), "
        "and chain heads own exactly two active reports each, which is tidier than a real catalog.",
        "Lineage is table-level only (no column lineage) and every table belongs to one hand-designed DAG.",
        "Dates are consistent by construction, but seasonality and business cycles are not modelled.",
        "Everything is in English; names come from Faker's en_US locale.",
    ]:
        add(f"- {line}")
    add("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Write the data card from generated data.")
    parser.add_argument("--data", type=Path, default=ROOT / "data")
    parser.add_argument("--out", type=Path, default=ROOT / "docs" / "data_card.md")
    args = parser.parse_args(argv)
    card = build_card(args.data)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_bytes(card.encode("utf-8"))
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
